### ISSUE TITLE
error when running train.py

### ISSUE THREAD

**Issue by Parisa-Bagherzadeh** [andrewyguo/dope_training#5]
![image](https://github.com/andrewyguo/dope_training/assets/71878421/4696b338-44a0-4541-8de5-82a568d4c62a)
what's the problem here?

**Comment by andrewyguo** [comment]
hi @Parisa-Bagherzadeh , please see the new repo that contains the updated training code: 

https://github.com/NVlabs/Deep_Object_Pose
